Update de.Json [Patch-1]
DexterHuang/CyberCodeOnline pull request #1834
Opened 2022-02-09 21:19 UTC by Xx-DragonSinns-xX

2022-02-09 22:40 UTC, Xx-DragonSinns-xX commented
ups

2022-02-09 23:05 UTC, Xx-DragonSinns-xX commented
howly mowly why i'm so bad at this 😢😂

2022-02-11 04:09 UTC, Pr0dam commented on contribution/lang/de.json
> + 	 	 	 	"trans": "Gangs und Ausrüstungsmerkmale",
This should read as Enemy gangs ( as its talking about the npc gang's Voodoo etc )

2022-02-11 04:12 UTC, Pr0dam requested changes
Just the one issue i can see, I left a comment on item 3271 so you should be able to see

2022-02-12 07:46 UTC, kt0t0Sudd3n commented
I'll add those myself if you don't mind

2022-02-12 08:21 UTC, Xx-DragonSinns-xX commented
@kt0t0Sudd3n 

No problem thanks :)

2022-02-12 09:04 UTC, merged