Mackerels0x00 patch 2
DexterHuang/CyberCodeOnline pull request #3208
Opened 2023-04-10 14:59 UTC by mackerels0x00

Update japanese translations for SLANC.

2023-04-10 20:47 UTC, YANDEREsenpaiXD requested changes
1部修正をお願いします。
コメントを参照してください。

2023-04-10 20:47 UTC, YANDEREsenpaiXD commented on contribution/mobile/ja/ai/knowledge.md
> +### dexとは誰のことですか？
dex❌
Dex⭕

2023-04-10 20:47 UTC, YANDEREsenpaiXD commented on contribution/mobile/ja/tutorial/ai.md
> +- "xxxxのやり方は？" や "xxxxとは何ですか？" のようなゲームの事実に関すること
How to xxx~ ここの例は英語のままでokです。

2023-04-11 00:38 UTC, mackerels0x00 commented
@YANDEREsenpaiXD 
コメントいただいた箇所（とついでに他に冗長な表現の微修正）を反映済みです。確認お願いします。

2023-04-11 00:41 UTC, merged

2023-04-11 00:42 UTC, YANDEREsenpaiXD commented
> @YANDEREsenpaiXD 
> コメントいただいた箇所（とついでに他に冗長な表現の微修正）を反映済みです。確認お願いします。 

ありがとうございます。ご協力に感謝します。
お疲れ様でした。