Update es.json
DexterHuang/CyberCodeOnline pull request #3327
Opened 2023-10-08 04:22 UTC by PIXIE-KEVIN

+Ajuste en las demas lineas consecuentes a Respeto Callejero
+Cambio en una mal traducción del inventario a la hora de bloquear un objeto 
+Cambio una traducción confunsa a la hora de tradear
Lineas:
(699, 703, 2727, 3876, 3882, 7716, 7723, 7729, 7733, 8625, 8629, 8633)

2023-10-09 16:41 UTC, Ravenant1234 commented
Nice

2023-10-09 16:43 UTC, Ravenant1234 requested changes
En la línea 7733 quedaría mejor "Y debes ser de nivel 10 o superior"

2023-10-10 02:49 UTC, PIXIE-KEVIN commented
> En la línea 7733 quedaría mejor "Y debes ser de nivel 10 o superior"

Hola si ya hice el cambio gracias ʕ ᵔᴥᵔ ʔ

2023-10-10 18:13 UTC, merged

2023-10-10 18:13 UTC, kroliklapine commented
thank you for your contribution!

2023-10-10 18:44 UTC, PIXIE-KEVIN commented
> thank you for your contribution!

You're welcome, it was a pleasure